### ISSUE TITLE
Bug sidebar's link active when the file.md has the same name

### ISSUE THREAD

**Issue by edalgrin-work** [diegonvs/gatsby-boilerplate#108]
The links of the sidebar appear with the class "active" when there are 2 files (file.md) with the same name in 2 different directories

image1:
![image](https://user-images.githubusercontent.com/46778114/51971226-f36a0d80-2478-11e9-9ed1-d4fbe2007d21.png)

image2:
![image](https://user-images.githubusercontent.com/46778114/51970957-658e2280-2478-11e9-9b5c-467e441448b0.png)

The bug seems to be generated by the file names (image 2)

**Comment by diegonvs** [comment]
Fixed in https://github.com/diegonvs/gatsby-boilerplate/pull/117
