### ISSUE TITLE
Installing dependencies with npm install doesn't work

### ISSUE THREAD

**Issue by julien** [diegonvs/gatsby-boilerplate#118]
If you install the dependencies with 

```
npm i
``` 

npm will warn you about peer dependencies that need to be manually installed.

If you try to execute the `start` script with 

```
npm start 
```

node will throw an error because of missing dependencies

In order to get all the depencies you need to use 

```sh
yarn
```

We should avoid using 2 package managers

**Comment by diegonvs** [comment]
Makes sense for me. I'll fix README and Documentation.
